name: bizinuca
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  intl: ^0.16.0
  back_button_interceptor: ^4.2.3
  cloud_firestore: 0.13.0+1
  fluttie: ^0.5.0
  flutter_spinkit: "^4.1.1"
  http: ^0.12.0+2
  firebase_auth: ^0.15.3
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/tacos.png
    - images/tacos2.png
    - images/billiards.png
    - images/billiard3.png
    - images/c.png
    - images/ranking.png
    - images/logout5.png
    - images/billiardPerson.png
    - images/medal.png
    - images/exit.png
    - images/podium.png
    - images/top-three.png
    