name: bizinuca
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/tacos.png
    - images/tacos2.png
    - images/mesa.png
    - images/bolas.png
    - images/billiard2.png
    - images/billiards.png
    - images/billiard3.png
    - images/b.png
    - images/c.png
    - images/a.svg
    - images/ranking.png
    - images/logout.png
    - images/logout2.png
    - images/logout5.png
    - images/billiardPerson.png
    - images/snooker.png
    - images/pool.png
    